회원정보 조회 및 수정 기능 구현
KDT3MiniProjectTeam-7/Mini_Project_BE pull request #18
Opened 2023-02-15 14:46 UTC by ykim-yeji

## Motivation
 - 회원정보 조회 및 수정 controller, service, dto 작성
    

## Key Changes
 - MemberInfoController 작성
   - 회원정보 조회 메소드 구현
   -  회원정보 수정 메소드 구현
 
 - MemberInfoService 인터페이스 작성
 
 - MemberInfoService 클래스 작성
   - 전체 회원정보 조회 메소드 구현
   - 일부 회원정보 조회 메소드 구현
   - 일부 회원정보 수정 메소드 구현
   - 비밀번호 일치 검사 메소드 삭제
   - 만 나이 계산 메소드 구현
 
 - Member Repository 수정
   - findByEmail 메소드 추가

 - Member Entity 수정
   - Entity를 dto로 변환하는 메소드 구현
 
 - DTO 작성
   - 회원정보와 상태 정보 response dto 구현
   - 상태 정보 reponse dto 구현
   - 일부 회원정보 service dto 구현
   - 변경할 회원정보 request dto 구현
   - 변경할 회원정보 service dto 구현
   - 회원정보 기존 request와 response 삭제

 - 패키지 이름과 필드 이름 사소한 오타 수정

## To reviewers
30개 커밋 죄송합니다.. 어제 구현했던걸 거의 대부분 뜯어고쳐서 15일에 커밋된 것만 봐도 되지 않을까 합니다.

2023-02-15 14:47 UTC, ykim-yeji commented
[0903f2c](https://github.com/KDT3MiniProjectTeam-7/Mini_Project_BE/pull/18/commits/0903f2c9ee9b4119ba99d2fb8fbe8b164876bacb) 부터 15일에 커밋한 것입니다.

2023-02-16 04:23 UTC, CocoIsCat requested changes

2023-02-16 04:23 UTC, CocoIsCat commented on src/main/java/com/example/finance7/member/controller/MemberInfoController.java
> +    public StatusResponse findSomeMemberInfo() {
컨트롤러에 있는 로직 서비스단으로 옮겨주세요.
서비스 안에서 StatusResponse를 만들어서 리턴하는 방법으로 변경해야할 거 같습니다.

2023-02-16 04:23 UTC, CocoIsCat commented on src/main/java/com/example/finance7/member/controller/MemberInfoController.java
> +        String status = memberInfoService.updateSomeMemberInfo(memberUpdateInfoRequest.toDto());
마찬가지입니다.

2023-02-16 07:22 UTC, ykim-yeji commented on src/main/java/com/example/finance7/member/controller/MemberInfoController.java
> +    public StatusResponse findSomeMemberInfo() {
네 수정했습니다.

2023-02-16 07:23 UTC, ykim-yeji commented on src/main/java/com/example/finance7/member/controller/MemberInfoController.java
> +        String status = memberInfoService.updateSomeMemberInfo(memberUpdateInfoRequest.toDto());
이것도 수정했습니다.

2023-02-16 10:11 UTC, CocoIsCat approved these changes
코드 확인했습니다.

2023-02-16 10:12 UTC, merged

2023-02-18 00:18 UTC, ykim-yeji commented
close #19